# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-11.1

packages:
- './imj-prelude'
- './imj-base'
- './imj-benchmark'
- './imj-particlesystem'
- './imj-game-hamazed'
- './imj-profile'
- './imj-measure-stdout'

- location:
    git: https://github.com/OlivierSohn/GLFW-b.git
    commit: 9c4a7a1306e6a4f07a33897e773d87cc5e547178
  extra-dep: true
- location:
    git: https://github.com/OlivierSohn/bindings-GLFW.git
    commit: 02d8896984607e98de5a8b46872b8939863637af
  extra-dep: true
- location:
    git: https://github.com/OlivierSohn/clay.git
    commit: fabb12c7cffcf12d2eb51224409b1819f7cdd42f
  extra-dep: true

extra-deps:
- FTGL-2.1
# to build ghc-mod:
#- https://hackage.haskell.org/package/ghc-mod-5.9.0.0/candidate/ghc-mod-5.9.0.0.tar.gz
#- cabal-helper-0.8.0.0
#- extra-1.5.3
#- monad-journal-0.7.2
#- either-4.4.1.1
#allow-newer: true # for optparse-applicative, due to ghc-mod

flags: {}

extra-package-dbs: []

# for GC stats:
#   -with-rtsopts=-sstderr
#
# -fpedantic-bottoms is to catch errors that are masked by the compiler,
#   as explained in  https://ghc.haskell.org/trac/ghc/ticket/14521
ghc-options:
  "$locals": -threaded -fexcess-precision -optc-ffast-math -Wall -fpedantic-bottoms -Wredundant-constraints -rtsopts -with-rtsopts=-maxN4

# Whenever an option here changes, the corresponding modules should be recompiled:
rebuild-ghc-options: true
