# http://docs.haskellstack.org/en/stable/yaml_configuration/

# resolver by ghc version:
#
#   8.4.2:  nightly-2018-05-18
#   8.2.2:  lts-11.9
resolver: lts-11.9

image:
  container:
    # defined in ./docker-rt/Dockerfile
    base: imajuscule/imj-game-rt

    # base of ./docker-heroku/Dockerfile
    name: imajuscule/hamazed

    # removing the executables field will include all built executables.
    executables:
    - imj-game-synths-exe

packages:
- './imj-base'
- './imj-bindings-audio'
- './imj-game'
- './imj-game-tutorial-increment'
- './imj-game-hamazed'
- './imj-game-synths'
- './imj-serve-highscores'
- './imj-measure-stdout'
- './imj-music'
- './imj-particlesystem'
- './imj-prelude'
- './imj-profile'
- './imj-server'
- './imj-space'
- './imj-time'

- location:
    git: https://github.com/OlivierSohn/clay.git
    commit: 954476940190873094847939c5f0e6242e324000
  extra-dep: true
- location:
    git: https://github.com/OlivierSohn/mwc-random.git
    commit: 89a5657db7cf0a6b95a6fba8467445208f9313e6
  extra-dep: true

extra-deps:
- FTGL-2.1              # for all resolvers (not part of stackage)
- GLFW-b-3.2.1.0        # for 8.2.2 resolver
- bindings-GLFW-3.2.1.1 # for 8.2.2 resolver
# to build ghc-mod:
#- https://hackage.haskell.org/package/ghc-mod-5.9.0.0/candidate/ghc-mod-5.9.0.0.tar.gz
#- cabal-helper-0.8.0.0
#- extra-1.5.3
#- monad-journal-0.7.2
#- either-4.4.1.1
#allow-newer: true # for optparse-applicative, due to ghc-mod

flags: {}

extra-package-dbs: []

# for GC stats:
#   -with-rtsopts=-sstderr
#
# -with-rtsopts=-N : we use it just to set the parallel GC on, we will manually set the number of capabilities in the code.
#
# -fpedantic-bottoms : to catch errors that are masked by the compiler,
#   as explained in https://ghc.haskell.org/trac/ghc/ticket/14521
#
# -qa : makes the benchmarks on world creation slightly (~1%) faster.
#
# -feager-blackholing : removed since it is slower (3%) for world creation benchmarks.
ghc-options:
  "$locals": -threaded -fexcess-precision -optc-ffast-math -Wall -fpedantic-bottoms -Wredundant-constraints -rtsopts -with-rtsopts=-N -with-rtsopts=-qa

# Whenever an option here changes, the corresponding modules should be recompiled:
rebuild-ghc-options: true
