-- BEGIN template
-- | The source code for this module was generated by 'mkSeedsSourceFile'

{-# LANGUAGE NoImplicitPrelude #-}

module Imj.Random.MWC.Seeds
       ( deterministicMWCSeeds
       ) where

import           Data.Word(Word32)

-- | Provides seeds for MWC RNG, generated at the time the source was written
--  using 'acquireSeedSystem'.
deterministicMWCSeeds :: [[Word32]]
deterministicMWCSeeds =
-- END template
