-- | The source code for this module was generated by 'mkSeedsSourceFile'

{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE LambdaCase #-}

module Imj.Random.Util
       ( randUUID
       ) where

import           Imj.Prelude
import           Data.UUID
import           System.Random.MWC

randUUID :: IO UUID
randUUID = withSystemRandom . asGenIO $ \gen ->
  forM [0 :: Int ..3] (const $ uniform gen) >>= \case
    [w1,w2,w3,w4] -> return $ fromWords w1 w2 w3 w4
    _ -> error "logic"
